name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 4"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          set -ex
          sudo apt update
          sudo apt install xorriso grub-pc-bin grub-efi mtools make python3 dosfstools e2fsprogs squashfs-tools python3-yaml gcc wget curl unzip xz-utils debootstrap git erofs-utils zstd
          git clone https://github.com/bayramkarahan/linuxsystemcreateiso.git
          cd linuxsystemcreateiso
          sudo ./createIso.sh
          cd ..
          sudo mkdir -p /output
          sudo mv linuxsystemcreateiso/*.iso /output/xfce-weekly.iso
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "main"
          prerelease: false
          title: "weekly build"
          files: |
            /output/*
